#pragma once
#include "LogConsole.h"
#include "UselessWinFiles.h"
#include "LogConsole.h"
#include <lmcons.h>
#include <wx/wx.h>
#include <iostream>
#include <filesystem>
#include "ProcessManagement.h"
#include <TlHelp32.h>
#include <codecvt>
#include "main.h"
